# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

post_install do |installer|
        installer.pods_project.build_configurations.each do |config|
             config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        end
end

target 'FindConvenienceStore' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FindConvenienceStore
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SnapKit'

  target 'FindConvenienceStoreTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Stubber'
    pod 'Nimble'
    pod 'RxBlocking'
    pod 'RxTest'
  end

end
