# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SearchDaumBlog(MVVM)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SearchDaumBlog(MVVM)
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'

end
